<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\ProjectBuildProperties.targets" />

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<ProjectReference Include="..\TqkLibrary.Proxy.Reverse\TqkLibrary.Proxy.Reverse.csproj" />
		<ProjectReference Include="..\TqkLibrary.Proxy.Reverse.Transport.WebSocket\TqkLibrary.Proxy.Reverse.Transport.WebSocket.csproj" />
	</ItemGroup>

</Project>
