<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net6.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
		<RootNamespace>TqkLibrary.Proxy.Reverse.Transport.WebSockets</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\TqkLibrary.Proxy.Reverse\TqkLibrary.Proxy.Reverse.csproj" />
	</ItemGroup>

</Project>
