<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\ProjectBuildProperties.targets" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net6.0;net8.0</TargetFrameworks>
		<RootNamespace>TqkLibrary.Proxy.Reverse.Transport.WebSockets</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\TqkLibrary.Proxy.Reverse\TqkLibrary.Proxy.Reverse.csproj" />
	</ItemGroup>

</Project>
