name: NET6 Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      Solution_Name: TqkLibrary.Proxy.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: TestProxy\TestProxy.csproj             # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.


    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Execute unit tests
        run: dotnet test